In [108]:
import numpy as np

In [109]:
data = np.genfromtxt('data_class10.csv',delimiter=',')

In [110]:
n = data.shape[0]

In [111]:
k=6

In [112]:
center_idx = np.random.choice(n,k,replace=False)

In [113]:
centers = list()

In [114]:
for i in center_idx:
  centers.append(data[i].tolist())

In [115]:
centers

[[0.6612865811461042, 7.01300997818697],
 [4.6962033334045055, 5.758824517924375],
 [1.390780151681962, 9.287135595069586],
 [5.884915569314564, 5.2933060545455515],
 [8.188630255006453, 2.932358449198693],
 [0.9205981831685243, 1.14526647807646]]

In [116]:
centers = data[np.random.choice(n,k,replace=False)]

In [117]:
def calc_distance(a,b):
  dist = 0;
  for x1,x2 in zip(a,b):
    dist += (x1-x2)**2
  return dist**0.5

In [118]:
#it's a bad decision
for s in data:
  idx = -1
  min = 999
  for i,c in enumerate(centers):
    dst = calc_distance(s,c)
    if min>dst:
      min = dst
      idx = i

In [119]:
data[0]

array([0.20987452, 2.00290685])

In [120]:
centers[0]

array([8.07674311, 3.10793375])

In [121]:
((data[0]-centers[0])**2).sum()**0.5

7.944098811781947

In [122]:
((data[0]-centers[1])**2).sum()**0.5

16.656296282694672

In [123]:
distance = np.zeros((n,k))
for i in range(k):
  distance[:,i] = ((data-centers[i])**2).sum(axis=1)**0.5

In [124]:
closest = np.argmin(distance,axis=1)

In [125]:

for i in range(k):
  centers[i] = data[closest==i].mean(axis=0)

In [126]:
centers

array([[11.38944415,  4.09279888],
       [13.4395059 , 11.39868597],
       [ 3.30827942,  3.82991646],
       [12.48188519, 13.75576296],
       [ 1.04051891,  7.94372151],
       [ 5.24226803,  0.27842546]])

In [127]:
old_closest = closest.copy()

In [128]:
if all(old_closest==closest):
  break

SyntaxError: 'break' outside loop (2854372634.py, line 2)

In [ ]:
#you have to write a function kmeans()
def kmeans(X,k):
  pass

In [ ]:
from matplotlib import pyplot as plt

In [ ]:
plt.scatter(data[:,0],data[:,1],c=closest)
plt.scatter(centers[:,0],centers[:,1],marker='*')
plt.show()