## Import numpy (Install if it is not on the system

In [182]:
import numpy as np

## The Basics

In [183]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6], dtype='int16')

# Basic arithmatic operations
print(a * b)
print(a / b)
print(a + b)
print(a - b)
print(a ** b)

[ 4 10 18]
[0.25 0.4  0.5 ]
[5 7 9]
[-3 -3 -3]
[  1  32 729]


In [184]:
c = np.array([[9.0, 7.0, 8.0], [5.0, 6.0, 4.0]])
d = np.array([[3.0, 4.0, 8.0], [7.0, 6.0, 5.0]], dtype='float32')
print(f'{c}\n')
print(f'{d}\n')

print(f'{c * d}\n')
print(f'{c / d}\n')

[[9. 7. 8.]
 [5. 6. 4.]]

[[3. 4. 8.]
 [7. 6. 5.]]

[[27. 28. 64.]
 [35. 36. 20.]]

[[3.         1.75       1.        ]
 [0.71428571 1.         0.8       ]]


In [185]:
# Get dimension
print(f'{a.ndim}\n')
print(f'{b.ndim}\n')
print(f'{c.ndim}\n')
print(f'{d.ndim}\n')

1

1

2

2


In [186]:
# Get shape, returns the size (row, column)
print(f'{a.shape}\n')
print(f'{b.shape}\n')

print(f'{c.shape}\n')
print(f'{d.shape}\n')

(3,)

(3,)

(2, 3)

(2, 3)


In [187]:
# Get the data type
print(a.dtype)
print(b.dtype)

print(c.dtype)
print(d.dtype)

int32
int16
float64
float32


In [188]:
# Get the item size
print(a.itemsize) # This is dtype='int32'
print(b.itemsize) # This is dtype='int16'

print(c.itemsize) # This is dtype='float64'
print(d.itemsize) # This is dtype='float32'

4
2
8
4


In [189]:
# Get total size, nbytes = number of bytes
print(a.size * a.itemsize)
print(a.nbytes)
print(b.size * b.itemsize)
print(b.nbytes)

print(c.size * c.itemsize)
print(c.nbytes)
print(d.size * d.itemsize)
print(d.nbytes)


12
12
6
6
48
48
24
24


## Accessing and changing specific elements, rows, columns etc

In [190]:
e = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(e)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [191]:
# Get specific elements
print(f'{e[1, 5]}\n')
print(f'{e[1, -2]}\n')

13

13


In [192]:
# Get a specific row
print(f'{e[0, :]}\n')
print(f'{e[1, :]}\n')

[1 2 3 4 5 6 7]

[ 8  9 10 11 12 13 14]


In [193]:
# Get a specific column
print(f'{e[:, 2]}')
e[:, 3]

[ 3 10]


array([ 4, 11])

In [194]:
# Getting a little more fancy [startindex:endindex:stepsize]
print(e[0, 2:7:2])
print(e[0, 1:6:2])
print(e[0, 1:-1:2])
print(e[1, 2:-2:1])

[3 5 7]
[2 4 6]
[2 4 6]
[10 11 12]


In [205]:
# Setting values
e[1,3] = 25
# print(e)

e[:, 2] = 7
# print(e)

e[:, 5] = [15, 16]
print(e)

[[ 1  2  7  4  5 15  7]
 [ 8  9  7 25 12 16 14]]
