In [20]:
import math

import numpy as np

In [21]:
path = 'offline_5_data.csv'
data = np.genfromtxt(path, delimiter=',')

n = data.shape[0]

In [22]:
n

1200

In [23]:
k = 6

cluster_centers = data[np.random.choice(n, k, replace=False)]

In [24]:
print(cluster_centers)

[[ 6.3955977   5.32186907]
 [ 5.94888053  4.30333424]
 [ 1.60248703  7.75112588]
 [ 6.73244556  1.12903664]
 [ 7.20474668  1.08135666]
 [ 0.84223561 -0.51864916]]


In [25]:
data[0]

array([0.20987452, 2.00290685])

In [26]:
cluster_centers[0]

array([6.3955977 , 5.32186907])

In [113]:
# Initialize 2 2D lists named "Clusters" and "Temp_Clusters"
clusters = list()
# temp_clusters = list()

In [114]:
# temp_clusters = [[] for _ in range(k)]
# for i, sample in enumerate(data):
#     min_distance_idx = np.argmin(np.linalg.norm(sample - cluster_centers, axis=1))
#     temp_clusters[min_distance_idx].append(i)

In [115]:
# temp_clusters

In [116]:
# Determine distance between "S" and "C".
distance = np.zeros((n, k))
for i in range(k):
    distance[:, i] = ((data-cluster_centers[i])**2).sum(axis=1) ** 0.5

In [117]:
distance.shape

(1200, 6)

In [135]:
Temp_Clusters = [[] for _ in range(cluster_centers.shape[0])]

closest_center_indices = np.argmin(distance, axis=1)
for sample_idx, center_idx in enumerate(closest_center_indices):
    Temp_Clusters[center_idx].append(sample_idx)

In [138]:
# closest_center_indices

In [140]:
# len(Temp_Clusters)

In [128]:
# temp_clusters = np.argmin(distance, axis=1)

In [141]:
# len(temp_clusters)

In [142]:
for i in range(k):
  cluster_centers[i] = data[Temp_Clusters==i].mean(axis=0)

C:\Users\subhe\AppData\Local\Temp\ipykernel_15224\28725192.py:2: RuntimeWarning: Mean of empty slice.
  cluster_centers[i] = data[Temp_Clusters==i].mean(axis=0)
C:\Users\subhe\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\_methods.py:184: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(


ValueError: could not broadcast input array from shape (1200,2) into shape (2,)

In [109]:
new_centers

array([0.99761199, 1.01477809])