## Function

In [58]:
# def fn_name(parameter):
#   function_body

def sum(a, b):
  c = a+b
  return c

print(sum(3,4))
print(sum('a','b'))

7
ab


In [59]:
def hello(name):
  name = name.capitalize()
  print('Hello ',name)

hello('rashed')
#hello(1)

Hello  Rashed


In [60]:
def test(arr):
  return (arr+arr)
print(test([1,2,3,4,5]))
print(test(100))
print(test("good"))

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
200
goodgood


In [61]:
def minmax(arr):
  return min(arr),max(arr)
min_, max_ = minmax([1,0,9,8,-1])
print(f'min:{min_}, max:{max_}')

a = minmax([1,0,9,8,-1])
print(a[0],a[1])

min:-1, max:9
-1 9


In [62]:
def canvote(is_citizen, age=0):
    if not is_citizen:
        print("can't vote", age)
        return False
    if age >= 18:
        print("can vote at the age", age)
        return True
    else:
        print("can't vote at the age", age)
        return False

print(canvote(True, 132), '\n')
print(canvote(False, age=31), '\n')
#print(canvote(), '\n') # error: missing 1 argument
#print(canvote(is_citizen=False, 31), '\n') # error: positional argument follows keyword argument

can vote at the age 132
True 

can't vote 31
False 


# Practice on function

## Tuple

In [63]:
tuple1 = ('red', 1, True, 'Yellow', 4.5,'Yellow')
print(tuple1)
print(len(tuple1))
print(tuple1[2])

('red', 1, True, 'Yellow', 4.5, 'Yellow')
6
True


In [64]:
if 'red' in tuple1:
  print('found')
else:
  print('Not found')

found


In [65]:
# We can't insert or delete item in a tuple
# Rather we can concate two tuple
# convert to list then add
tuple2 = ("Green",)
tuple1 += tuple2
print(tuple1)
print(tuple2)

('red', 1, True, 'Yellow', 4.5, 'Yellow', 'Green')
('Green',)


In [66]:
x = list(tuple1)
x.append('Magenta')
tuple1 = tuple(x)
print(tuple1)

('red', 1, True, 'Yellow', 4.5, 'Yellow', 'Green', 'Magenta')


In [67]:
thisTuple = (1,"apple",True,[1,2])
*x, y = thisTuple
print(x,y)

[1, 'apple', True] [1, 2]


In [68]:
x,*_,y = tuple1
print(x,y)

red Magenta


In [69]:
for item in tuple1:
  print(item)

red
1
True
Yellow
4.5
Yellow
Green
Magenta


In [70]:
for item in range(len(tuple1)):
  print(tuple1[item])

red
1
True
Yellow
4.5
Yellow
Green
Magenta


## Set


In [71]:
set1 = {"apple","banana",1,"apple"}
print(set1)

{1, 'banana', 'apple'}


In [72]:
set1 = {"apple","banana",1,"apple",True}
print(set1)

{1, 'banana', 'apple'}


In [73]:
set1.add("mango")
print(set1)

{1, 'banana', 'apple', 'mango'}


In [74]:
set2 = {"yellow","banana"}
set1.update(set2)
print(set1)

{1, 'yellow', 'mango', 'banana', 'apple'}


In [75]:
set1.remove("yellow")
print(set1)

{1, 'mango', 'banana', 'apple'}


In [76]:
# set can't access by index
for x in set1:
  print(x)

1
mango
banana
apple


## List

In [77]:
arr = ['apple', 'grape', 100, 3.4,[1,2],(2,3)]
print(arr)
print(arr[:2])

['apple', 'grape', 100, 3.4, [1, 2], (2, 3)]
['apple', 'grape']


In [78]:
arr.append('orange')
print(arr)

['apple', 'grape', 100, 3.4, [1, 2], (2, 3), 'orange']


In [79]:
arr.insert(1,560)
print(arr)

['apple', 560, 'grape', 100, 3.4, [1, 2], (2, 3), 'orange']


In [80]:
print(arr.pop(1))
print(arr)

560
['apple', 'grape', 100, 3.4, [1, 2], (2, 3), 'orange']


In [81]:
print(arr.remove("grape"))
print(arr)

None
['apple', 100, 3.4, [1, 2], (2, 3), 'orange']


In [82]:
if 'apple' in arr:
  print('found')
else:
  print('Not found')

found


In [83]:
print(len(arr))

6


In [84]:
for item in arr:
  print(item)

apple
100
3.4
[1, 2]
(2, 3)
orange


In [85]:
for i in range(len(arr)):
  print(arr[i])

apple
100
3.4
[1, 2]
(2, 3)
orange


In [86]:
temp = [1,2,3,4,5]
print(temp*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [87]:
arr2 = temp
arr2.append(6)
print(temp,arr2)

[1, 2, 3, 4, 5, 6] [1, 2, 3, 4, 5, 6]


In [88]:
arr2 = temp.copy()
arr2.append(7)
print(temp,arr2)

[1, 2, 3, 4, 5, 6] [1, 2, 3, 4, 5, 6, 7]


In [89]:
foo = [1, 2, []]
bar = foo
bar[-1].append(4)
print(foo, bar, '\n')

foo = [1, 2, []]
bar = foo.copy()
bar[-1].append(5)
print(foo, bar, '\n')

import copy
foo = [1, 2, []]
bar = copy.deepcopy(foo)
bar[-1].append(5)
print(foo, bar, '\n')

[1, 2, [4]] [1, 2, [4]] 

[1, 2, [5]] [1, 2, [5]] 

[1, 2, []] [1, 2, [5]] 


## Print all pair of numbers from a list

In [90]:
A = [1,2,3,4]

## Print a relation is reflexive or symmetric or transitive or not?

In [91]:
R = {(1,1),(1,2),(2,2),(2,3),(3,3),(3,2),(4,4)}

## Dictionary

In [92]:
person = {
    "name" : "saiful islam ratan",
    "email" : "ratan@bscse.uiu.ac.bd",
    "joined" : 2019,
    "course" : ["SPL","AI","DSA"]
}

In [93]:
print(person)
print(person.keys())
print(person.values())

{'name': 'saiful islam ratan', 'email': 'ratan@bscse.uiu.ac.bd', 'joined': 2019, 'course': ['SPL', 'AI', 'DSA']}
dict_keys(['name', 'email', 'joined', 'course'])
dict_values(['saiful islam ratan', 'ratan@bscse.uiu.ac.bd', 2019, ['SPL', 'AI', 'DSA']])


In [94]:
print(person.get('joined'))
print(person['joined'])
print("name" in person)

2019
2019
True


In [95]:
for key in person:
  print(key,"--->",person[key])

name ---> saiful islam ratan
email ---> ratan@bscse.uiu.ac.bd
joined ---> 2019
course ---> ['SPL', 'AI', 'DSA']


In [96]:
print(person.pop('course'))
print(person)

person['course'] = ["OOP","AOOP"]
print(person)

['SPL', 'AI', 'DSA']
{'name': 'saiful islam ratan', 'email': 'ratan@bscse.uiu.ac.bd', 'joined': 2019}
{'name': 'saiful islam ratan', 'email': 'ratan@bscse.uiu.ac.bd', 'joined': 2019, 'course': ['OOP', 'AOOP']}


## write a code that counts the frequency of each letter in a sentence

In [97]:
graph = {
    "A":["B","C","D"],
    "B" : ["A","C","D"],
    "C" :["A","B","E"],
    "D" :["A","B","E"],
    "E" :["C","D"]
    }

In [98]:
for vertex in graph:
  print(vertex,"->",graph[vertex])

A -> ['B', 'C', 'D']
B -> ['A', 'C', 'D']
C -> ['A', 'B', 'E']
D -> ['A', 'B', 'E']
E -> ['C', 'D']


## Class in python

In [99]:
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def __str__(self):
    return f"{self.name}({self.age})"

p1 = Person("John", 36)

print(p1)

John(36)


In [100]:
class Employee:
  emp_num = 0 # works like static variable common to all objects of a class

  def __init__(self, first, last, pay): # constructor
    self.first = first # member variable
    self.last = last # member variable
    self.email = first + '.' + last + '@email.com' # member variable
    self.pay = pay # member variable
    apple = 1 # not member variable
    Employee.emp_num += 1 # static variable

  def fullname(self): # self is comparable to this keyword of Java
    return f'{self.first} {self.last}'# "%s %s", self.first, self.last
  
  def applyRaise(self, raise_):
    self.pay = int(self.pay * raise_)

  def __str__(self): # toString()
    return f'{self.fullname()} - {self.email}: {self.pay}'

  @staticmethod # (Decorator) same working procedure for all objects of a class 
  def is_holiday(day):
    holidays = [1, 30, 49, 350]
    if day in holidays:
        return True
    else:
      return False


In [101]:
print(Employee.emp_num) # 0

emp_1 = Employee('Corey', 'Schafer', 50000) 
emp_2 = Employee('Test', 'Employee', 60000)


print(Employee.emp_num) # 2

print(emp_1.fullname()) # Corey Schafer

emp_1.applyRaise(1.5)
print(emp_1.pay) # 75000

print(Employee.is_holiday(30)) # True
print(Employee.is_holiday(31)) # False

print(emp_1) # Corey Schafer corey.schafer@gmail.com 75000

0
2
Corey Schafer
75000
True
False
Corey Schafer - Corey.Schafer@email.com: 75000


In [102]:
class Developer(Employee):
    def __init__(self, first, last, pay, prog_lang):
        super().__init__(first, last, pay) # call parent class constructor
        self.prog_lang = prog_lang


class Manager(Employee):
  def __init__(self, first, last, pay, employees=None):
      super().__init__(first, last, pay)
      if employees is None:
          self.employees = []
      else:
          self.employees = employees

  def add_emp(self, emp):
      if emp not in self.employees:
          self.employees.append(emp)

  def remove_emp(self, emp):
      if emp in self.employees:
          self.employees.remove(emp)

  def print_emps(self):
      for emp in self.employees:
          print('-->', emp.fullname())


In [103]:
dev_1 = Developer('Corey', 'Schafer', 50000, 'Python')
dev_2 = Developer('Test', 'Employee', 60000, 'Java')

mgr_1 = Manager('Sue', 'Smith', 90000, [dev_1])
print(mgr_1.email)

mgr_1.add_emp(dev_2)
mgr_1.print_emps()
print()

mgr_1.remove_emp(dev_2)
mgr_1.print_emps()
print()

print(isinstance(mgr_1, Manager))  # Is mgr_1 an instance of Manager? 
print(isinstance(mgr_1, Employee))
print(isinstance(mgr_1, Developer))
print()

print(issubclass(Developer, Employee)) # Is Developer class a subclass of Employee class??

Sue.Smith@email.com
--> Corey Schafer
--> Test Employee

--> Corey Schafer

True
True
False

True


## write a class Point to store the x,y coords of 2D points. 
1. The class should have the methods move_left, move_right, move_up, move down.
2. move_left moves the point 1 cell to the left, move_right moves the point 1 cell to the right
3. move_up moves the point 1 cell up, and move_down moves the point 1 cell down
4. write a distance function to calculate the manhattan distance between two points

## Numpy

In [104]:
# numpy tutorial - http://cs231n.github.io/python-numpy-tutorial/#numpy-arrays
# numpy uses the facility of GPU. So, try to use it instead of for loop
import numpy as np 

In [105]:
a = [3, 6, 7]
print(type(a))
arr = np.array(a)
print(type(arr))

print(arr.shape)

<class 'list'>
<class 'numpy.ndarray'>
(3,)


In [106]:
a = [
     [1, 4],
     [3, 5]
]
a = np.array(a)
print(a.shape)

(2, 2)


In [107]:
a = np.array([3, 5, 4])
print(type(a))
print(a.shape)
print(a[0])

<class 'numpy.ndarray'>
(3,)
3


In [108]:
a = np.random.random((4, 5))
print(a)
a = np.random.randint(0, 10, (4, 5))
# a = np.random.randint(low=0, high=10, size=(4, 5))
print(a)

[[0.26504308 0.83343251 0.29129027 0.12849559 0.39463734]
 [0.13648753 0.50518057 0.11740957 0.96041346 0.27104103]
 [0.19033538 0.30466295 0.17557356 0.602259   0.7368125 ]
 [0.52900852 0.39076841 0.16307193 0.30744775 0.67211903]]
[[3 6 4 0 9]
 [0 7 2 5 8]
 [1 4 3 2 7]
 [9 7 1 8 0]]


In [109]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]


In [110]:
x = np.array([[1,2],[3,4]]) 
y = np.array([[5,6],[7,8]])

print(x + y)
print(np.add(x, y)) #time complexity O(1) if we use GPU

print( x+100 )
print((x+100) / 2)

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[101 102]
 [103 104]]
[[50.5 51. ]
 [51.5 52. ]]


In [111]:
z= x/y
print(z)
z = x*y # element wise multiplication
print(z)
print(x.dot(y)) # matrix multiplication / dot product
print(np.dot(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [112]:
x = np.array([
              [1,2,5],
              [3,4,1]
              ])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[8 8]"

16
[4 6 6]
[8 8]


In [113]:
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# print(v * w) # can't do this, need to reshape

v = np.reshape(v, (3, 1))
print(v)
print(v.shape)
print(w.shape)

print(v * w)

[[1]
 [2]
 [3]]
(3, 1)
(2,)
[[ 4  5]
 [ 8 10]
 [12 15]]


## Pandas

In [114]:
import pandas as pd

In [115]:
mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [116]:
myvar.head()

cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2